version: '3.9'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:latest
    networks:
      - frontend
    depends_on:
      - nginx 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build:
      context: ./app
    depends_on:
      - nginx  
      - redis  
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 5s
      timeout: 3s
      retries: 3

  mongodb1:
    image: mongo:latest
    volumes:
      - mongo_data_1:/data/db
    networks:
      - backend
    depends_on:
      - app  
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb2:
    image: mongo:latest
    volumes:
      - mongo_data_2:/data/db
    networks:
      - backend
    depends_on:
      - app  
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongo_data_1:
  mongo_data_2:

networks:
  frontend:
  backend: